name: Build C++ Project

on:
  push:
    branches: [ BORBA-v1.2-OS projekat ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++

    - name: Build project
      run: make

    - name: Run (test basic functionality)
      run: ./borba < /dev/null